name: Pull Request Labeller

on:
  pull_request:

jobs:
  labeller:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        sync-labels: true
